<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Kontena.Core\Kontena.Core.csproj" />
    <ProjectReference Include="..\Kontena.Core.Orchestration\Kontena.Core.Orchestration.csproj" />
    <ProjectReference Include="..\Kontena.Engines\Kontena.Engines.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
